server:
  port: 8082
  contextPath: 
spring:
  jpa:    
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.datasource: 
  type: com.zaxxer.hikari.HikariDataSource
  url: jdbc:postgresql://192.168.56.108:5433/test
  username: postgres
  password: 1234
  testWhileIdle: true
  validationQuery: SELECT 1
flyway:
  schemas:
    - public
  metaDataTableName: schema_version